Meteor.startup(function () {
  if (Items.find().count() === 0) {
    var names = [
      "Vanilla Ice Cream",
      "Vanilla Ice Cream, Philadelphia-Style",
      "Chocolate Ice Cream",
      "Chocolate Ice Cream, Philadelphia-Style",
      "Aztec “Hot” Chocolate Ice Cream",
      "Chocolate–Peanut Butter Ice Cream",
      "Chocolate-Raspberry Ice Cream",
      "Milk Chocolate Ice Cream",
      "Guinness–Milk Chocolate Ice Cream",
      "White Chocolate Ice Cream",
      "Coffee Ice Cream",
      "Coffee Frozen Yogurt",
      "Vietnamese Coffee Ice Cream",
      "Anise Ice Cream",
      "Cinnamon Ice Cream",
      "Black Currant Tea Ice Cream",
      "Green Tea Ice Cream",
      "Kinako Ice Cream",
      "Fresh Ginger Ice Cream",
      "Butterscotch Pecan Ice Cream",
      "Date, Rum, and Pecan Ice Cream",
      "Gianduja Gelato",
      "Maple Walnut Ice Cream with Wet Walnuts",
      "Vanilla Frozen Yogurt",
      "Peanut Butter Ice Cream",
      "Orange Popsicle Ice Cream",
      "Malted Milk Ice Cream",
      "Oatmeal-Raisin Ice Cream",
      "Rum Raisin Ice Cream",
      "Tin Roof Ice Cream",
      "Zabaglione Gelato",
      "Chartreuse Ice Cream",
      "Eggnog Ice Cream",
      "Crème Fraîche Ice Cream",
      "Toasted Almond and Candied Cherry Ice Cream",
      "Goat Cheese Ice Cream",
      "Cheesecake Ice Cream",
      "Tiramisù Ice Cream",
      "Lavender-Honey Ice Cream",
      "Roquefort-Honey Ice Cream",
      "Turrón Ice Cream",
      "Sweet Potato Ice Cream with Maple-Glazed Pecans",
      "Panforte Ice Cream",
      "Rice Gelato",
      "Roasted Banana Ice Cream",
      "Sour Cherry Frozen Yogurt",
      "Dried Apricot–Pistachio Ice Cream",
      "Fresh Apricot Ice Cream",
      "Plum Ice Cream",
      "Prune-Armagnac Ice Cream",
      "Pear-Caramel Ice Cream",
      "Fresh Fig Ice Cream",
      "Pear-Pecorino Ice Cream",
      "Olive Oil Ice Cream",
      "Orange–Szechwan Pepper Ice Cream",
      "Super Lemon Ice Cream",
      "Lemon-Speculoos Ice Cream",
      "Blueberry Frozen Yogurt",
      "Peach Ice Cream",
      "Peach Frozen Yogurt",
      "Strawberry–Sour Cream Ice Cream",
      "Strawberry Frozen Yogurt",
      "Raspberry Swirl Ice Cream",
      "Raspberry Ice Cream",
      "Passion Fruit Ice Cream",
      "Avocado Ice Cream",
      "Toasted Coconut Ice Cream",
      "Green Pea Ice Cream",
      "Fresh Mint Ice Cream",
      "Basil Ice Cream",
      "Parsley Ice Cream",
      "Black Pepper Ice Cream",
      "Saffron Ice Cream"];
    for (var i = 0; i < names.length; i++) {
      Items.insert({name: names[i], score: 1400, gamesCount: 0});
    }
  }
});